services:
  tartar:
    image: imprevisible/tartar:latest
    ports:
      - "8088:80"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - GOOGLE_PLACES_API_KEY=${GOOGLE_PLACES_API_KEY}
      - OTP_CODE=${OTP_CODE} # 123456 for example
      - VITE_OTP_FORMAT=${VITE_OTP_FORMAT} # XXX-XXX for example
    restart: unless-stopped
