export const currencies = [{
    "value": "usd",
    "label": "USD",
    "icon": "🇺🇸",
    "symbol": "$"
}, {
    "value": "eur",
    "label": "EUR",
    "icon": "🇪🇺",
    "symbol": "€"
}, {
    "value": "jpy",
    "label": "JPY",
    "icon": "🇯🇵",
    "symbol": "¥"
}, {
    "value": "gbp",
    "label": "GBP",
    "icon": "🇬🇧",
    "symbol": "£"
}, {
    "value": "aud",
    "label": "AUD",
    "icon": "🇦🇺",
    "symbol": "AU$"
}, {
    "value": "cad",
    "label": "CAD",
    "icon": "🇨🇦",
    "symbol": "C$"
}, {
    "value": "chf",
    "label": "CHF",
    "icon": "🇨🇭",
    "symbol": "Fr."
}, {
    "value": "cny",
    "label": "CNY",
    "icon": "🇨🇳",
    "symbol": "¥"
}, {
    "value": "sek",
    "label": "SEK",
    "icon": "🇸🇪",
    "symbol": "kr"
}, {
    "value": "nzd",
    "label": "NZD",
    "icon": "🇳🇿",
    "symbol": "NZ$"
}, {
    "value": "inr",
    "label": "INR",
    "icon": "🇮🇳",
    "symbol": "₹"
}, {
    "value": "rub",
    "label": "RUB",
    "icon": "🇷🇺",
    "symbol": "₽"
}, {
    "value": "brl",
    "label": "BRL",
    "icon": "🇧🇷",
    "symbol": "R$"
}, {
    "value": "zar",
    "label": "ZAR",
    "icon": "🇿🇦",
    "symbol": "R"
}, {
    "value": "mxn",
    "label": "MXN",
    "icon": "🇲🇽",
    "symbol": "Mex$"
}, {
    "value": "sgd",
    "label": "SGD",
    "icon": "🇸🇬",
    "symbol": "S$"
}, {
    "value": "hkd",
    "label": "HKD",
    "icon": "🇭🇰",
    "symbol": "HK$"
}, {
    "value": "krw",
    "label": "KRW",
    "icon": "🇰🇷",
    "symbol": "₩"
}, {
    "value": "try",
    "label": "TRY",
    "icon": "🇹🇷",
    "symbol": "₺"
}, {
    "value": "aed",
    "label": "AED",
    "icon": "🇦🇪",
    "symbol": "د.إ"
}, {
    "value": "sar",
    "label": "SAR",
    "icon": "🇸🇦",
    "symbol": "ر.س"
}, {
    "value": "nok",
    "label": "NOK",
    "icon": "🇳🇴",
    "symbol": "kr"
}, {
    "value": "dkk",
    "label": "DKK",
    "icon": "🇩🇰",
    "symbol": "kr."
}, {
    "value": "pln",
    "label": "PLN",
    "icon": "🇵🇱",
    "symbol": "zł"
}, {
    "value": "huf",
    "label": "HUF",
    "icon": "🇭🇺",
    "symbol": "Ft"
}, {
    "value": "czk",
    "label": "CZK",
    "icon": "🇨🇿",
    "symbol": "Kč"
}, {
    "value": "ils",
    "label": "ILS",
    "icon": "🇮🇱",
    "symbol": "₪"
}, {
    "value": "clp",
    "label": "CLP",
    "icon": "🇨🇱",
    "symbol": "$"
}, {
    "value": "php",
    "label": "PHP",
    "icon": "🇵🇭",
    "symbol": "₱"
}, {
    "value": "thb",
    "label": "THB",
    "icon": "🇹🇭",
    "symbol": "฿"
}, {
    "value": "idr",
    "label": "IDR",
    "icon": "🇮🇩",
    "symbol": "Rp"
}, {
    "value": "myr",
    "label": "MYR",
    "icon": "🇲🇾",
    "symbol": "RM"
}, {
    "value": "ron",
    "label": "RON",
    "icon": "🇷🇴",
    "symbol": "L"
}, {
    "value": "cop",
    "label": "COP",
    "icon": "🇨🇴",
    "symbol": "$"
}, {
    "value": "pkr",
    "label": "PKR",
    "icon": "🇵🇰",
    "symbol": "₨"
}, {
    "value": "egp",
    "label": "EGP",
    "icon": "🇪🇬",
    "symbol": "E£"
}, {
    "value": "kes",
    "label": "KES",
    "icon": "🇰🇪",
    "symbol": "KSh"
}, {
    "value": "ngn",
    "label": "NGN",
    "icon": "🇳🇬",
    "symbol": "₦"
}, {
    "value": "vnd",
    "label": "VND",
    "icon": "🇻🇳",
    "symbol": "₫"
}, {
    "value": "qar",
    "label": "QAR",
    "icon": "🇶🇦",
    "symbol": "QR"
}, {
    "value": "bdt",
    "label": "BDT",
    "icon": "🇧🇩",
    "symbol": "৳"
}, {
    "value": "twd",
    "label": "TWD",
    "icon": "🇹🇼",
    "symbol": "NT$"
}, {
    "value": "uah",
    "label": "UAH",
    "icon": "🇺🇦",
    "symbol": "₴"
}, {
    "value": "ars",
    "label": "ARS",
    "icon": "🇦🇷",
    "symbol": "$"
}, {
    "value": "pen",
    "label": "PEN",
    "icon": "🇵🇪",
    "symbol": "S/."
}, {
    "value": "vef",
    "label": "VEF",
    "icon": "🇻🇪",
    "symbol": "Bs."
}, {
    "value": "hrk",
    "label": "HRK",
    "icon": "🇭🇷",
    "symbol": "kn"
}, {
    "value": "bgn",
    "label": "BGN",
    "icon": "🇧🇬",
    "symbol": "лв."
}, {
    "value": "isk",
    "label": "ISK",
    "icon": "🇮🇸",
    "symbol": "kr"
}, {
    "value": "xaf",
    "label": "XAF",
    "icon": "🇨🇲",
    "symbol": "FCFA"
}, {
    "value": "xof",
    "label": "XOF",
    "icon": "🇧🇫",
    "symbol": "CFA"
}, {
    "value": "xpf",
    "label": "XPF",
    "icon": "🇵🇫",
    "symbol": "₣"
}, {
    "value": "dzd",
    "label": "DZD",
    "icon": "🇩🇿",
    "symbol": "د.ج"
}, {
    "value": "tnd",
    "label": "TND",
    "icon": "🇹🇳",
    "symbol": "د.ت"
}, {
    "value": "bam",
    "label": "BAM",
    "icon": "🇧🇦",
    "symbol": "KM"
}, {
    "value": "gel",
    "label": "GEL",
    "icon": "🇬🇪",
    "symbol": "₾"
}, {
    "value": "amd",
    "label": "AMD",
    "icon": "🇦🇲",
    "symbol": "֏"
}, {
    "value": "azn",
    "label": "AZN",
    "icon": "🇦🇿",
    "symbol": "₼"
}, {
    "value": "kzt",
    "label": "KZT",
    "icon": "🇰🇿",
    "symbol": "₸"
}, {
    "value": "uzs",
    "label": "UZS",
    "icon": "🇺🇿",
    "symbol": "soʻm"
}, {
    "value": "tjs",
    "label": "TJS",
    "icon": "🇹🇯",
    "symbol": "SM"
}, {
    "value": "kgs",
    "label": "KGS",
    "icon": "🇰🇬",
    "symbol": "Som"
}, {
    "value": "tmt",
    "label": "TMT",
    "icon": "🇹🇲",
    "symbol": "T"
}, {
    "value": "afn",
    "label": "AFN",
    "icon": "🇦🇫",
    "symbol": "؋"
}, {
    "value": "lak",
    "label": "LAK",
    "icon": "🇱🇦",
    "symbol": "₭"
}, {
    "value": "mmk",
    "label": "MMK",
    "icon": "🇲🇲",
    "symbol": "K"
}, {
    "value": "lbp",
    "label": "LBP",
    "icon": "🇱🇧",
    "symbol": "L£"
}, {
    "value": "jod",
    "label": "JOD",
    "icon": "🇯🇴",
    "symbol": "د.أ"
}, {
    "value": "omr",
    "label": "OMR",
    "icon": "🇴🇲",
    "symbol": "ر.ع."
}, {
    "value": "kwd",
    "label": "KWD",
    "icon": "🇰🇼",
    "symbol": "د.ك"
}, {
    "value": "bhk",
    "label": "BHD",
    "icon": "🇧🇭",
    "symbol": ".د.ب"
}, {
    "value": "iqd",
    "label": "IQD",
    "icon": "🇮🇶",
    "symbol": "د.ع"
}, {
    "value": "irr",
    "label": "IRR",
    "icon": "🇮🇷",
    "symbol": "﷼"
}, {
    "value": "syp",
    "label": "SYP",
    "icon": "🇸🇾",
    "symbol": "£S"
}, {
    "value": "yer",
    "label": "YER",
    "icon": "🇾🇪",
    "symbol": "﷼"
}, {
    "value": "lkr",
    "label": "LKR",
    "icon": "🇱🇰",
    "symbol": "Rs"
}, {
    "value": "bnd",
    "label": "BND",
    "icon": "🇧🇳",
    "symbol": "B$"
}, {
    "value": "mop",
    "label": "MOP",
    "icon": "🇲🇴",
    "symbol": "MOP$"
}, {
    "value": "mur",
    "label": "MUR",
    "icon": "🇲🇺",
    "symbol": "₨"
}, {
    "value": "mwk",
    "label": "MWK",
    "icon": "🇲🇼",
    "symbol": "K"
}, {
    "value": "mga",
    "label": "MGA",
    "icon": "🇲🇬",
    "symbol": "Ar"
}, {
    "value": "rwf",
    "label": "RWF",
    "icon": "🇷🇼",
    "symbol": "FRw"
}, {
    "value": "aoa",
    "label": "AOA",
    "icon": "🇦🇴",
    "symbol": "Kz"
}, {
    "value": "bif",
    "label": "BIF",
    "icon": "🇧🇮",
    "symbol": "FBu"
}, {
    "value": "djf",
    "label": "DJF",
    "icon": "🇩🇯",
    "symbol": "Fdj"
}, {
    "value": "etb",
    "label": "ETB",
    "icon": "🇪🇹",
    "symbol": "Br"
}, {
    "value": "ern",
    "label": "ERN",
    "icon": "🇪🇷",
    "symbol": "Nkf"
}, {
    "value": "gmd",
    "label": "GMD",
    "icon": "🇬🇲",
    "symbol": "D"
}, {
    "value": "gnf",
    "label": "GNF",
    "icon": "🇬🇳",
    "symbol": "FG"
}, {
    "value": "htg",
    "label": "HTG",
    "icon": "🇭🇹",
    "symbol": "G"
}, {
    "value": "jmd",
    "label": "JMD",
    "icon": "🇯🇲",
    "symbol": "J$"
}, {
    "value": "kmf",
    "label": "KMF",
    "icon": "🇰🇲",
    "symbol": "CF"
}, {
    "value": "mvr",
    "label": "MVR",
    "icon": "🇲🇻",
    "symbol": "Rf"
}, {
    "value": "mzn",
    "label": "MZN",
    "icon": "🇲🇿",
    "symbol": "MT"
}, {
    "value": "nad",
    "label": "NAD",
    "icon": "🇳🇦",
    "symbol": "N$"
}, {
    "value": "scr",
    "label": "SCR",
    "icon": "🇸🇨",
    "symbol": "SR"
}, {
    "value": "sll",
    "label": "SLL",
    "icon": "🇸🇱",
    "symbol": "Le"
}, {
    "value": "sos",
    "label": "SOS",
    "icon": "🇸🇴",
    "symbol": "Sh.So."
}, {
    "value": "srd",
    "label": "SRD",
    "icon": "🇸🇷",
    "symbol": "$"
}, {
    "value": "szl",
    "label": "SZL",
    "icon": "🇸🇿",
    "symbol": "L"
}, {
    "value": "tzd",
    "label": "TZS",
    "icon": "🇹🇿",
    "symbol": "TSh"
}, {
    "value": "ugx",
    "label": "UGX",
    "icon": "🇺🇬",
    "symbol": "USh"
}, {
    "value": "xcd",
    "label": "XCD",
    "icon": "🇦🇬",
    "symbol": "$"
}, {
    "value": "xdr",
    "label": "XDR",
    "icon": "🌐",
    "symbol": "SDR"
}, {
    "value": "xpd",
    "label": "XPD",
    "icon": "🌐",
    "symbol": "Pd"
}, {
    "value": "xpt",
    "label": "XPT",
    "icon": "🌐",
    "symbol": "Pt"
}, {
    "value": "xag",
    "label": "XAG",
    "icon": "🌐",
    "symbol": "Ag"
}, {
    "value": "xau",
    "label": "XAU",
    "icon": "🌐",
    "symbol": "Au"
}, {
    "value": "all",
    "label": "ALL",
    "icon": "🇦🇱",
    "symbol": "L"
}, {
    "value": "awg",
    "label": "AWG",
    "icon": "🇦🇼",
    "symbol": "Afl"
}, {
    "value": "bsd",
    "label": "BSD",
    "icon": "🇧🇸",
    "symbol": "B$"
}, {
    "value": "bhd",
    "label": "BHD",
    "icon": "🇧🇭",
    "symbol": ".د.ب"
}, {
    "value": "bbd",
    "label": "BBD",
    "icon": "🇧🇧",
    "symbol": "Bds$"
}, {
    "value": "bzn",
    "label": "BZD",
    "icon": "🇧🇿",
    "symbol": "BZ$"
}, {
    "value": "bmd",
    "label": "BMD",
    "icon": "🇧🇲",
    "symbol": "BD$"
}, {
    "value": "btn",
    "label": "BTN",
    "icon": "🇧🇹",
    "symbol": "Nu."
}, {
    "value": "bob",
    "label": "BOB",
    "icon": "🇧🇴",
    "symbol": "Bs"
}, {
    "value": "bwp",
    "label": "BWP",
    "icon": "🇧🇼",
    "symbol": "P"
}, {
    "value": "byn",
    "label": "BYN",
    "icon": "🇧🇾",
    "symbol": "Br"
}, {
    "value": "khr",
    "label": "KHR",
    "icon": "🇰🇭",
    "symbol": "៛"
}, {
    "value": "cve",
    "label": "CVE",
    "icon": "🇨🇻",
    "symbol": "$"
}, {
    "value": "crc",
    "label": "CRC",
    "icon": "🇨🇷",
    "symbol": "₡"
}, {
    "value": "cup",
    "label": "CUP",
    "icon": "🇨🇺",
    "symbol": "$"
}, {
    "value": "dop",
    "label": "DOP",
    "icon": "🇩🇴",
    "symbol": "RD$"
}, {
    "value": "fjd",
    "label": "FJD",
    "icon": "🇫🇯",
    "symbol": "FJ$"
}, {
    "value": "gtq",
    "label": "GTQ",
    "icon": "🇬🇹",
    "symbol": "Q"
}, {
    "value": "hnl",
    "label": "HNL",
    "icon": "🇭🇳",
    "symbol": "L"
}, {
    "value": "kpw",
    "label": "KPW",
    "icon": "🇰🇵",
    "symbol": "₩"
}, {
    "value": "kyd",
    "label": "KYD",
    "icon": "🇰🇾",
    "symbol": "CI$"
}, {
    "value": "npr",
    "label": "NPR",
    "icon": "🇳🇵",
    "symbol": "रु"
}, {
    "value": "nio",
    "label": "NIO",
    "icon": "🇳🇮",
    "symbol": "C$"
}, {
    "value": "pgk",
    "label": "PGK",
    "icon": "🇵🇬",
    "symbol": "K"
}, {
    "value": "pyg",
    "label": "PYG",
    "icon": "🇵🇾",
    "symbol": "₲"
}, {
    "value": "rsd",
    "label": "RSD",
    "icon": "🇷🇸",
    "symbol": "din"
}, {
    "value": "sdg",
    "label": "SDG",
    "icon": "🇸🇩",
    "symbol": "£SD"
}, {
    "value": "shp",
    "label": "SHP",
    "icon": "🇸🇭",
    "symbol": "£"
}, {
    "value": "ssp",
    "label": "SSP",
    "icon": "🇸🇸",
    "symbol": "£"
}, {
    "value": "std",
    "label": "STD",
    "icon": "🇸🇹",
    "symbol": "Db"
}, {
    "value": "svc",
    "label": "SVC",
    "icon": "🇸🇻",
    "symbol": "$"
}, {
    "value": "top",
    "label": "TOP",
    "icon": "🇹🇴",
    "symbol": "T$"
}, {
    "value": "ttd",
    "label": "TTD",
    "icon": "🇹🇹",
    "symbol": "TT$"
}, {
    "value": "uyu",
    "label": "UYU",
    "icon": "🇺🇾",
    "symbol": "$U"
}, {
    "value": "vuv",
    "label": "VUV",
    "icon": "🇻🇺",
    "symbol": "VT"
}, {
    "value": "wst",
    "label": "WST",
    "icon": "🇼🇸",
    "symbol": "WS$"
}, {
    "value": "zmw",
    "label": "ZMW",
    "icon": "🇿🇲",
    "symbol": "K"
}] 
